name: CI

on:
  push:
    branches: [ master ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Show hour ubuntu
        run: timedatectl
        
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Show hour windows
        run: Get-Date
        
  macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Show hour mac
        run: date +%Y-%m-%d
        
  depend_others_jobs:
    runs-on: ubuntu-latest
    needs: [ubuntu, windows, macOS]
    steps:
      - uses: actions/checkout@v2

      - name: Show hour ubuntu depend others jobs
        run: timedatectl
